version: '3.8'

services:
  webapp:
    build: ./webapp
    ports:
      - "8080:80"
    environment:
      MYSQL_HOST: database
      MYSQL_USER: root
      MYSQL_PASSWORD: toor123!
      MYSQL_DATABASE: vulnmart
    volumes:
      - ./webapp/uploads:/var/www/html/uploads
    depends_on:
      - database
    networks:
      - vulnmart-network

  database:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: toor123!
      MYSQL_DATABASE: vulnmart
    ports:
      - "3306:3306"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql_data:/var/lib/mysql
    networks:
      - vulnmart-network

  admin_service:
    build: ./admin_service
    networks:
      - vulnmart-network

networks:
  vulnmart-network:
    driver: bridge

volumes:
  mysql_data:
